export const FORECAST_CITY_SELECTED = "FORECAST_CITY_SELECTED";
export const ENTER_FORECAST_APP = "ENTER_FORECAST_APP";
export const CITY_FETCH_COMPLETE = "CITY_FETCH_COMPLETE";
export const CHANGE_SELECTED_CITY = "CHANGE_SELECTED_CITY";
export const TOGGLE_CITY_FAVORITE = "TOGGLE_CITY_FAVORITE";
export const FETCH_FAILED_ERROR = "FETCH_FAILED_ERROR";
